'use client';

import { useEffect, useState } from 'react';

const projects = [
  { n: '01', title: 'Образовательная платформа', type: 'В разработке', text: 'Образовательная платформа. Демонстрационная версия временно недоступна.', tags: ['Web platform'], url: 'https://nashen1.onrender.com', accent: 'orbit' },
  { n: '02', title: 'СЭН', type: 'Beauty / Astana', text: 'Лендинг салона: 8 категорий услуг, прайс с вкладками, история, галерея, отзывы и запись.', tags: ['HTML', 'CSS', 'JavaScript'], url: 'https://nurdauletbeisenbek7-web.github.io/CEN_SALON/', accent: 'rose' },
  { n: '03', title: 'Ханшайым', type: 'Beauty / Astana', text: 'Премиальный лендинг с услугами, прайсом, галереей, отзывами и контактами.', tags: ['HTML', 'CSS', 'JavaScript'], url: 'https://nurdauletbeisenbek7-web.github.io/Khanshaiym/', accent: 'violet' },
  { n: '04', title: 'JOALI Spa & Relax', type: 'Thai spa / Almaty', text: 'Структура салона: карточки мастеров, меню процедур, отзывы и удобная связь через WhatsApp.', tags: ['HTML', 'CSS', 'JavaScript'], url: 'https://nurdauletbeisenbek7-web.github.io/JOALI/', accent: 'sand' },
  { n: '05', title: 'UBT BASE', type: 'Flagship · AI for education', text: 'Платформа подготовки к ЕНТ: тесты, мгновенная проверка, ИИ-разбор ошибок и дашборд прогресса.', tags: ['Next.js', 'Vercel', 'OpenAI API'], url: 'https://ubtbase-92yo.vercel.app', accent: 'ai', featured: true },
  { n: '06', title: 'Delish', type: 'Cafe', text: 'Полный сайт кафе с меню, собранным на основе реальных техкарт заказчика.', tags: ['HTML', 'CSS', 'JavaScript', 'Vercel'], url: 'https://delish-iota.vercel.app/', accent: 'lime' },
  { n: '07', title: 'Wedding invitation', type: 'Event', text: 'Анимированное приглашение: таймер, программа, RSVP, KZ/RU-интерфейс, Calendar и Maps.', tags: ['Next.js', 'Vercel'], url: 'https://weeding-eta-sooty.vercel.app', accent: 'peach' },
  { n: '08', title: 'Dental Clinic Astana', type: 'Healthcare', text: 'Многостраничный сайт: каталог 6 направлений и ~25 услуг, навигация и быстрые контакты.', tags: ['HTML', 'CSS', 'JavaScript'], url: 'https://nurdauletbeisenbek7-web.github.io/DENTALastana/services.html#orthodontics', accent: 'blue' },
];

function Arrow() { return <span className="arrow">↗</span>; }

export default function Home() {
  const [menu, setMenu] = useState(false); const [sent, setSent] = useState(false); const [loading, setLoading] = useState(false);
  useEffect(() => { const observer = new IntersectionObserver((entries) => entries.forEach(e => e.isIntersecting && e.target.classList.add('visible')), { threshold: .12 }); document.querySelectorAll('.reveal').forEach(x => observer.observe(x)); return () => observer.disconnect(); }, []);
  async function submit(e) { e.preventDefault(); setLoading(true); const form = new FormData(e.currentTarget); const res = await fetch('/api/contact', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(Object.fromEntries(form)) }); setLoading(false); if (res.ok) { setSent(true); e.currentTarget.reset(); } else alert((await res.json()).error); }
  return <main>
    <nav><a className="brand" href="#top">NB<span>.</span></a><button className="menu" onClick={() => setMenu(!menu)} aria-label="Открыть меню">{menu ? '×' : '☰'}</button><div className={menu ? 'navlinks open' : 'navlinks'}><a href="#about">Обо мне</a><a href="#work">Проекты</a><a href="#contact" className="nav-cta">Связаться <Arrow /></a></div></nav>
    <section className="hero" id="top"><div className="grid-bg" /><div className="hero-copy"><p className="eyebrow"><i /> AVAILABLE FOR PROJECTS</p><h1>Нурдаулет<br/><em>Бейсенбек.</em></h1><p className="intro">Создаю понятные цифровые продукты для реального бизнеса — и учусь строить интеллект для будущего.</p><div className="hero-actions"><a href="#work" className="button">Смотреть проекты <Arrow /></a><a href="#contact" className="text-link">Начать разговор ↓</a></div></div><div className="portrait-wrap"><div className="halo"/><div className="portrait"><img src="/portrait.jpg" alt="Нурдаулет Бейсенбек"/></div><p className="portrait-label">WEB DEVELOPER<br/>FUTURE ML ENGINEER</p></div><div className="hero-bottom"><span>SCROLL TO EXPLORE</span><b>↓</b><span>17 y.o. · Qairu University</span></div></section>
    <section id="about" className="about section"><p className="section-label reveal">01 / ОБО МНЕ</p><div className="about-grid"><h2 className="reveal">Любопытство —<br/><em>мой главный стек.</em></h2><div className="about-text reveal"><p>Мне 17. Я поступил на грант в <strong>Qairu</strong> — AI-enabled университет, где начинаю путь в Machine Learning.</p><p>Пока учусь, уже проектирую и собираю сайты для настоящих бизнесов. Мне нравится момент, когда идея превращается в работающий продукт.</p><div className="facts"><div><b>6.0</b><span>IELTS</span></div><div><b>01</b><span>грант Qairu</span></div><div><b>×</b><span>призёр респ. олимпиад</span></div></div></div></div></section>
    <section className="skills section"><p className="section-label reveal">02 / ИНСТРУМЕНТЫ</p><div className="skills-head reveal"><h2>Осваиваю основу.<br/><em>Собираю результат.</em></h2><p>Честно: это мой базовый, но уже применяемый на реальных проектах стек.</p></div><div className="skill-list">{[['Python','01','логика и данные'],['HTML','02','структура продукта'],['CSS','03','визуальный язык'],['SQL','04','данные и запросы']].map(([name,num,desc]) => <div className="skill reveal" key={name}><span>{num}</span><b>{name}</b><p>{desc}</p><div className="skill-line"/></div>)}</div></section>
    <section id="work" className="work section"><div className="work-title reveal"><p className="section-label">03 / ВЫБРАННЫЕ РАБОТЫ</p><h2>Реальные задачи.<br/><em>Живые продукты.</em></h2></div><div className="projects">{projects.map(p => <article className={`project ${p.featured ? 'featured' : ''} reveal`} key={p.n}><div className={`project-visual ${p.accent}`}><span>{p.n}</span><div className="visual-shape"/>{p.featured && <div className="ai-word">AI<br/><small>LEARN / ANALYZE / GROW</small></div>}</div><div className="project-info"><p className="project-type">{p.type}</p><h3>{p.title}</h3><p className="project-text">{p.text}</p><div className="project-foot"><div className="tags">{p.tags.map(t => <span key={t}>{t}</span>)}</div><a aria-label={`Открыть ${p.title}`} href={p.url} target="_blank" rel="noreferrer"><Arrow /></a></div></div></article>)}</div></section>
    <section id="contact" className="contact section"><div className="contact-copy reveal"><p className="section-label">04 / КОНТАКТ</p><h2>Есть идея?<br/><em>Давайте сделаем.</em></h2><p>Напишите пару слов о задаче — я отвечу и предложу, с чего начать.</p><div className="direct-links"><a href="tel:+77028246092">+7 702 824 6092 <Arrow /></a><a href="https://github.com/nurdauletbeisenbek7-web" target="_blank" rel="noreferrer">GitHub <Arrow /></a><a href="https://www.instagram.com/nurda.b.n" target="_blank" rel="noreferrer">Instagram <Arrow /></a><span>LinkedIn · nurdaulet beisenbek</span></div></div><form className="contact-form reveal" onSubmit={submit}>{sent ? <div className="success"><b>Сообщение отправлено.</b><p>Спасибо! Скоро свяжусь с вами.</p><button type="button" onClick={() => setSent(false)}>Отправить ещё</button></div> : <><label>Как к вам обращаться?<input name="name" placeholder="Ваше имя" required /></label><label>Как с вами связаться?<input name="contact" placeholder="Telegram, телефон или email" required /></label><label>О чём проект?<textarea name="message" placeholder="Расскажите кратко о задаче" required rows="4"/></label><button className="submit" disabled={loading}>{loading ? 'Отправляю…' : <>Отправить сообщение <Arrow /></>}</button><small>Сообщение придёт мне напрямую в Telegram.</small></>}</form></section>
    <footer><a className="brand" href="#top">NB<span>.</span></a><span>© 2026 Нурдаулет Бейсенбек</span><span>Made with curiosity.</span></footer>
  </main>;
}
