'use client';

import { useEffect, useState } from 'react';

const projects = [
  { title: 'UBT BASE', label: 'Главный проект · EdTech / AI', text: 'Собственный сервис подготовки к ЕНТ по математике и информатике: тесты по 20 вопросов, мгновенная проверка, ИИ-разбор ошибок, отслеживание слабых тем и личный прогресс.', stack: 'Next.js · Vercel · OpenAI API', url: 'https://ubtbase-92yo.vercel.app', main: true },
  { title: 'СЭН', label: 'Сайт для салона красоты · Астана', text: 'Лендинг с восемью категориями услуг, табами прайса, историей салона с 1993 года, отзывами и блоком записи. Добавил WhatsApp, Google Maps, 2GIS и метатеги для превью ссылок.', stack: 'HTML · CSS · JavaScript', url: 'https://nurdauletbeisenbek7-web.github.io/CEN_SALON/' },
  { title: 'Ханшайым', label: 'Премиальный beauty-лендинг · Астана', text: 'Визуальный лендинг с акцентом на рейтинг 4.9 и 500+ клиенток. Реализовал бегущую строку на CSS, OpenStreetMap и переходы в WhatsApp и Instagram.', stack: 'HTML · CSS · JavaScript', url: 'https://nurdauletbeisenbek7-web.github.io/Khanshaiym/' },
  { title: 'Dental Clinic Astana', label: 'Многостраничный сайт клиники', text: 'Структура из шести направлений и примерно 25 услуг. Внутри страницы услуг сделал навигацию по якорям, добавил click-to-call и быстрый переход в WhatsApp.', stack: 'HTML · CSS · JavaScript', url: 'https://nurdauletbeisenbek7-web.github.io/DENTALastana/services.html#orthodontics' },
  { title: 'JOALI Spa & Relax', label: 'Тайский спа-салон · Алматы', text: 'Собрал удобную структуру контента: мастера, процедуры по категориям, отзывы и WhatsApp-ссылка с заранее подготовленным текстом сообщения.', stack: 'HTML · CSS · JavaScript', url: 'https://nurdauletbeisenbek7-web.github.io/JOALI/' },
  { title: 'Delish', label: 'Сайт кафе', text: 'Полный сайт кафе. Меню наполнено реальными данными из техкарт заказчика, а проект подготовлен к размещению на Vercel.', stack: 'HTML · CSS · JavaScript · Vercel', url: 'https://delish-iota.vercel.app/' },
  { title: 'Wedding invitation', label: 'Сайт-приглашение', text: 'Переиспользуемый шаблон с анимацией, таймером, программой, RSVP-формой, KZ/RU-интерфейсом, Google Calendar и картой.', stack: 'Next.js · Vercel', url: 'https://weeding-eta-sooty.vercel.app' },
  { title: 'Образовательная платформа', label: 'В разработке', text: 'Образовательная платформа. Демонстрационная версия сейчас временно недоступна.', stack: 'Web platform', url: 'https://nashen1.onrender.com', draft: true },
];
const skills = [
  ['Python', 'базовый уровень'], ['HTML', 'семантическая вёрстка'], ['CSS', 'адаптив и анимации'], ['JavaScript', 'интерактив в браузере'], ['React', 'компонентный интерфейс'], ['Next.js', 'сайты и API-маршруты'], ['SQL', 'основы работы с данными'], ['REST API', 'интеграции в проектах'], ['OpenAI API', 'ИИ-функции в UBT BASE'], ['Vercel', 'деплой веб-проектов'],
];

export default function Home() {
  const [menu, setMenu] = useState(false); const [sent, setSent] = useState(false); const [loading, setLoading] = useState(false);
  useEffect(() => { const o = new IntersectionObserver(es => es.forEach(e => e.isIntersecting && e.target.classList.add('in')), { threshold: .08 }); document.querySelectorAll('.show').forEach(e => o.observe(e)); return () => o.disconnect(); }, []);
  async function submit(e) { e.preventDefault(); setLoading(true); const response = await fetch('/api/contact', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(Object.fromEntries(new FormData(e.currentTarget))) }); setLoading(false); if (response.ok) { setSent(true); e.currentTarget.reset(); } else alert((await response.json()).error); }
  return <main>
    <header><a className="mark" href="#start">НБ<span>—</span></a><button className="mobile-menu" onClick={() => setMenu(!menu)}>{menu ? 'Закрыть' : 'Меню'}</button><nav className={menu ? 'open' : ''}><a href="#about">Обо мне</a><a href="#projects">Проекты</a><a href="#contact">Контакты</a></nav><a className="header-action" href="#contact">Обсудить задачу <b>↘</b></a></header>
    <section id="start" className="intro-block"><div className="intro-meta"><span>Портфолио / 2026</span><span>Веб-разработка<br/>и путь в ML</span></div><div className="intro-name"><p>Привет, меня зовут</p><h1>Нурдаулет<br/><i>Бейсенбек</i></h1></div><div className="intro-side"><div className="photo"><img src="/portrait.jpg" alt="Нурдаулет Бейсенбек" /></div><p>Студент Qairu<br/>и веб-разработчик</p></div><div className="intro-summary"><p>Создаю сайты для бизнеса и развиваюсь в Machine Learning. Мне важно, чтобы проект был не просто красивым, а понятным и работал на задачу.</p><a href="#projects">Посмотреть работы <b>↓</b></a></div></section>
    <section id="about" className="about-block"><div className="rail show">ОБО МНЕ</div><div className="about-main show"><h2>Учусь на ML-инженера.<br/>Уже делаю сайты <i>для бизнеса.</i></h2><div className="about-columns"><p>Мне 17 лет. Я поступил на грант в Qairu — AI-enabled университет, где изучаю направление Machine Learning. До университета окончил школу и участвовал в республиканских олимпиадах.</p><p>Сейчас беру веб-задачи для реальных клиентов: собираю структуру, вёрстку, интерфейс и интеграции. Такой опыт помогает мне видеть продукт целиком, а не только код.</p></div></div><aside className="credentials show"><div><b>Qairu</b><span>грант · ML-направление</span></div><div><b>IELTS 6.0</b><span>английский язык</span></div><div><b>Олимпиады</b><span>призёр республиканских</span></div></aside></section>
    <section className="skills-block"><div className="skills-title show"><span>ТЕХНОЛОГИИ</span><h2>То, с чем<br/>я <i>работаю.</i></h2><p>Уровень разный: часть инструментов изучаю, часть уже применил в проектах. Не приписываю себе то, чего не делал.</p></div><div className="skill-cloud show">{skills.map(([name, detail]) => <div className="skill-chip" key={name}><b>{name}</b><span>{detail}</span></div>)}</div></section>
    <section id="projects" className="projects-block"><div className="project-heading show"><span>ПРОЕКТЫ</span><h2>Работы, которые<br/><i>можно открыть.</i></h2><p>Сайты для сферы услуг, образовательные продукты и проекты с современным стеком.</p></div><article className="lead-project show"><div className="lead-number">01</div><div className="lead-content"><p>ГЛАВНЫЙ ПРОЕКТ / EDTECH</p><h3>UBT<br/>BASE</h3><p className="lead-text">Подготовка к ЕНТ с ИИ-разбором ошибок</p><a href={projects[0].url} target="_blank" rel="noreferrer">Открыть проект <b>↗</b></a></div><div className="lead-details"><p>{projects[0].text}</p><span>{projects[0].stack}</span><div className="dot-field">✦　·　✦<br/>　·　✦　·</div></div></article><div className="cases">{projects.slice(1).map((p, index) => <article className={`case show ${p.draft ? 'draft' : ''}`} key={p.title}><div className="case-index">0{index + 2}</div><div className="case-content"><p>{p.label}</p><h3>{p.title}</h3><p className="case-text">{p.text}</p></div><div className="case-bottom"><span>{p.stack}</span><a href={p.url} target="_blank" rel="noreferrer" aria-label={`Открыть ${p.title}`}>↗</a></div></article>)}</div></section>
    <section id="contact" className="contact-block"><div className="contact-top show"><span>СВЯЗЬ</span><h2>Давайте обсудим<br/><i>вашу задачу.</i></h2></div><div className="contact-layout"><div className="contact-direct show"><p>Можно написать через форму — сообщение придёт мне в Telegram. Или связаться напрямую:</p><a href="tel:+77028246092">+7 702 824 6092 <b>↗</b></a><a href="tg://resolve?phone=77028246092">Открыть Telegram <b>↗</b></a><a href="https://www.instagram.com/nurda.b.n" target="_blank" rel="noreferrer">Instagram <b>↗</b></a><a href="https://github.com/nurdauletbeisenbek7-web" target="_blank" rel="noreferrer">GitHub <b>↗</b></a><a href="https://www.linkedin.com/in/nurdaulet-beisenbek/" target="_blank" rel="noreferrer">LinkedIn <b>↗</b></a></div><form className="message-form show" onSubmit={submit}>{sent ? <div className="sent"><b>Сообщение отправлено.</b><p>Спасибо, отвечу в ближайшее время.</p><button type="button" onClick={() => setSent(false)}>Написать ещё раз</button></div> : <><label>Имя<input name="name" required placeholder="Как к вам обращаться?" /></label><label>Контакт<input name="contact" required placeholder="Telegram, телефон или email" /></label><label>Сообщение<textarea name="message" rows="4" required placeholder="Кратко опишите задачу" /></label><button disabled={loading}>{loading ? 'Отправляю…' : 'Отправить в Telegram ↗'}</button><small>Данные не сохраняются на сайте.</small></>}</form></div></section>
    <footer><a className="mark" href="#start">НБ<span>—</span></a><span>© 2026 Нурдаулет Бейсенбек</span><span>Qairu / Казахстан</span></footer>
  </main>;
}
